### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by antonio-borriello** [cSandrini/pvpsystem-resource#1]
Hello, nice work. I was wondering if it was possible to include rounds in matches. Really nice work

**Comment by cSandrini** [comment]
Hello, thanks! Yes, it is. But I have no intentions of continuing this project currently. By the way, you can make changes as you like.

**Comment by antonio-borriello** [comment]
okok thank you! Have a good day

**Comment by cSandrini** [comment]
> Hello, nice work. I was wondering if it was possible to include rounds in matches. Really nice work
I'm working on this project again and it's a nice suggestion...

**Comment by cSandrini** [comment]
I'm working on this project again and it's a nice suggestion...

**Comment by ghost** [comment]
Any Updates on this?
